# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbfa8e35d455a943d3d3b6e44999429507cbd6fe65da0dabfc81f1599dfb97d039907bff8d7c2b2d325d650fca9bd46844cc152abf512b97e3d6cdcaf639e931

test:
  secret_key_base: 2f185d6fbb980cad14d61ddc3dcb6b42e585d34fd5958327a9324f590cc488aa22f6594fa26e3a90c6e7a09832416bf915ebec8f43e19c46c42c5f37d7d5bc21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
